on: push

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x
      - name: Format
        run: deno fmt
      - name: Lint
        run: deno lint
